### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by xynorez** [BME-MIT-IET/IBH-iet-2018#12]

**Comment by xynorez** [comment]
Added DifferentTriples test.
Added GraphRemoveTriples test.

**Comment by OmTheTurtle** [comment]
Added GraphSerialization test.

**Comment by Mozes96** [comment]
Added GraphSet test

**Comment by xynorez** [comment]
Added Container test.

**Comment by Mozes96** [comment]
Added Collection test

**Comment by kellerkruz** [comment]
Added Namespace test
