### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by xynorez** [BME-MIT-IET/IBH-iet-2018#13]
Find a suitable method to check code coverage on our tests.

**Comment by Mozes96** [comment]
codecov lets see

**Comment by Mozes96** [comment]
codeacy:
Error Prone
100%
Performance
100%
Security
100%
Unused Code
100%
no issues

**Comment by xynorez** [comment]
Codecov.io reports are not working. Trying to find a fix.

**Comment by OmTheTurtle** [comment]
ReSharper dotCover tool: 16% coverage for the full solution.

**Comment by OmTheTurtle** [comment]
Code coverage is complete with 21% overall project coverage and a 53% result on the RDFSharp.Model namespace. We wrote 7 test classes with 32 test cases.
